# Generated by Django 3.2.9 on 2022-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userreg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
