# Generated by Django 3.2.9 on 2022-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('bookauthor', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/image/ % Y/% m/% d/')),
                ('sr', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
