# Generated by Django 3.2.9 on 2022-02-07 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstatus',
            name='bname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
